pkg/operator/starter.go

Set the operator as removable

---

config/manifests/preview/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml

STOR-956: Add PDB permissions

---

config/manifests/preview/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml

STOR-956: Add additional permissions for resizer and snapshotter sidecars

---

assets/rbac/snapshotter_role.yaml

OCPBUGS-346: Fix snapshotter permissions

---

assets/controller.yaml
test/e2e/manifest.yaml

STOR-964: Adjust configuration for e2e testing

---

config/manifests/preview/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml

STOR-956: Add additional patch permission for snapshotter

---

config/manifests/preview/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml

OCPBUGS-384: Fix ClusterServiceVersion.Spec.Description

---

config/manifests/preview/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml

Add a note stating the support level

---

.ci-operator.yaml
Makefile
README.md
config/manifests/gcp-filestore-csi-driver-operator.package.yaml
config/manifests/preview/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml

Ref. https://issues.redhat.com/browse/ART-5087

OCPBUGS-4535: Bump version to 4.13

---

OWNERS

Adding Maxim as approver and updating component to reflect the current state of things.

Chore: update OWNERS file

---

Makefile
README.md
config/manifests/gcp-filestore-csi-driver-operator.package.yaml
config/manifests/stable/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml

https://issues.redhat.com/browse/STOR-1388
cc @openshift/storage

STOR-1388: Early chore: update OCP version in OLM metadata

---

Makefile
README.md
config/manifests/gcp-filestore-csi-driver-operator.package.yaml
config/manifests/stable/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml

Increase OCP version in OLM metadata.
@openshift/storage

STOR-1590: Bump OLM metadata to 4.16

---

config/manifests/preview/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml

OCPBUGS-30082: Add infrastructure annotations

---

config/manifests/preview/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml

OCPBUGS-30084: Add infrastructure annotations

---

Makefile
README.md
config/manifests/gcp-filestore-csi-driver-operator.package.yaml
config/manifests/stable/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml

https://issues.redhat.com/browse/STOR-1606

STOR-1606: Bump OLM metadata to 4.17

---

config/manifests/gcp-filestore-csi-driver-operator.package.yaml
config/manifests/stable/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml

https://issues.redhat.com/browse/STOR-2009
/label px-approved
/label docs-approved

STOR-2009: Bump OLM metadata to 4.18

---

config/manifests/gcp-filestore-csi-driver-operator.package.yaml
config/manifests/stable/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml

https://issues.redhat.com/browse/STOR-2260

STOR-2260: Bump OLM metadata to 4.19

---

config/manifests/stable/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml

https://issues.redhat.com/browse/STOR-1880

STOR-1880: Role and ClusterRole with too wide permissions

---

Makefile
README.md
config/manifests/gcp-filestore-csi-driver-operator.package.yaml
config/manifests/stable/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml

https://issues.redhat.com/browse/STOR-2408

STOR-2408: Bump OLM metadata to 4.20

---

Makefile
README.md
config/manifests/gcp-filestore-csi-driver-operator.package.yaml
config/manifests/stable/gcp-filestore-csi-driver-operator.clusterserviceversion.yaml
hack/update-metadata.sh

https://issues.redhat.com/browse/STOR-2600
/cc @openshift/storage-qe

STOR-2600, OCPBUGS-61437: Bump OLM metadata to 4.21
